// Intensity scales for nouns and verbs.
//
// Each entry is [partOfSpeech, sense, words], where `words` runs from the
// weakest word to the strongest. A word may appear in several scales when it
// has several senses (e.g. "worry" as a verb and as a noun).
//
// Rankings are judgement calls, not ground truth. Keep each scale to one
// meaning so that every step reads as "the same idea, but more (or less)".

export const SCALES = [
  // ── Verbs: feelings ──────────────────────────────────────────────────────
  ["verb", "feel aversion", "mind, dislike, hate, despise, detest, loathe, abhor"],
  ["verb", "feel affection", "like, fancy, love, adore, worship, idolize"],
  ["verb", "take pleasure in", "appreciate, enjoy, relish, savor, revel in"],
  ["verb", "want", "wish, want, desire, crave, yearn, lust"],
  ["verb", "be anxious", "wonder, worry, fret, agonize, obsess"],
  ["verb", "be afraid of", "worry, fear, dread"],
  ["verb", "be angry", "bristle, simmer, fume, seethe, rage"],
  ["verb", "hold in esteem", "respect, admire, revere, venerate, worship"],
  ["verb", "hold dear", "appreciate, value, cherish, treasure"],
  ["verb", "envy", "admire, envy, covet"],
  ["verb", "doubt", "question, doubt, distrust, disbelieve"],
  ["verb", "hold as true", "guess, suppose, think, believe, know"],
  ["verb", "understand", "follow, grasp, understand, comprehend, master"],

  // ── Verbs: affecting someone's feelings ──────────────────────────────────
  ["verb", "make angry", "bother, annoy, irritate, anger, infuriate, enrage"],
  ["verb", "make afraid", "unsettle, unnerve, alarm, frighten, terrify, petrify"],
  ["verb", "make happy", "satisfy, please, delight, thrill, elate"],
  ["verb", "make sad", "disappoint, sadden, upset, distress, devastate"],
  ["verb", "catch off guard", "surprise, amaze, astonish, astound, stun, flabbergast"],
  ["verb", "make ashamed", "fluster, embarrass, shame, humiliate, mortify"],
  ["verb", "make unsure", "puzzle, confuse, perplex, baffle, bewilder"],
  ["verb", "arouse interest", "interest, intrigue, excite, thrill, electrify"],
  ["verb", "spur on", "encourage, motivate, inspire, galvanize"],
  ["verb", "wear out", "tire, fatigue, weary, exhaust, drain"],

  // ── Verbs: speaking and reacting ─────────────────────────────────────────
  ["verb", "say aloud", "whisper, murmur, say, exclaim, shout, yell, scream"],
  ["verb", "cry", "sniffle, whimper, cry, weep, sob, bawl, wail"],
  ["verb", "laugh", "chuckle, giggle, laugh, cackle, guffaw, howl"],
  ["verb", "smile", "smirk, smile, grin, beam"],
  ["verb", "ask for", "ask, request, urge, plead, beg, implore"],
  ["verb", "propose", "suggest, recommend, advise, urge, insist, demand"],
  ["verb", "give orders", "instruct, direct, order, command, decree"],
  ["verb", "disagree", "disagree, bicker, argue, quarrel, fight, feud"],
  ["verb", "find fault", "question, critique, criticize, condemn, denounce, excoriate"],
  ["verb", "tell off", "chide, scold, reprimand, rebuke, berate, lambaste"],
  ["verb", "speak well of", "compliment, commend, praise, acclaim, extol, glorify"],
  ["verb", "express discontent", "grumble, complain, protest, rail, rant"],
  ["verb", "make fun of", "tease, taunt, mock, ridicule, deride"],
  ["verb", "caution", "remind, caution, warn, threaten"],
  ["verb", "persuade", "nudge, encourage, persuade, pressure, coerce, force"],
  ["verb", "back", "tolerate, accept, support, endorse, champion"],
  ["verb", "turn down", "decline, refuse, reject, rebuff, spurn"],
  ["verb", "pay no attention", "overlook, disregard, ignore, snub, shun, ostracize"],
  ["verb", "mislead", "fudge, fib, mislead, lie, deceive, defraud"],

  // ── Verbs: moving and acting ─────────────────────────────────────────────
  ["verb", "go on foot", "amble, stroll, walk, stride, march"],
  ["verb", "run", "jog, trot, run, race, sprint"],
  ["verb", "go down", "slip, stumble, fall, tumble, plunge, plummet"],
  ["verb", "eat", "nibble, snack, eat, gobble, devour, gorge"],
  ["verb", "drink", "sip, drink, gulp, guzzle, chug"],
  ["verb", "look", "glance, look, gaze, stare, gawk"],
  ["verb", "look over", "check, review, examine, inspect, scrutinize"],
  ["verb", "read", "skim, browse, read, study, pore over"],
  ["verb", "sleep", "doze, nap, sleep, slumber"],
  ["verb", "hold", "hold, grip, grasp, clutch, clench"],
  ["verb", "take hold of", "take, grab, snatch, seize"],
  ["verb", "hit", "tap, knock, hit, strike, whack, smash, pummel"],
  ["verb", "push", "nudge, push, shove, thrust, ram"],
  ["verb", "pull", "tug, pull, yank, wrench"],
  ["verb", "throw", "toss, throw, fling, hurl"],
  ["verb", "press together", "press, squeeze, squash, crush"],
  ["verb", "cut", "nick, scratch, cut, gash, slash, sever"],
  ["verb", "break", "chip, crack, break, shatter, smash, pulverize"],
  ["verb", "damage", "damage, ruin, wreck, destroy, devastate, annihilate, obliterate"],
  ["verb", "injure", "sting, hurt, injure, wound, maim"],
  ["verb", "kill", "kill, slay, slaughter, massacre, exterminate"],
  ["verb", "burn", "singe, scorch, burn, char, incinerate"],
  ["verb", "clean", "wipe, rinse, clean, wash, scrub, scour"],
  ["verb", "shake", "quiver, tremble, shake, shudder, convulse"],
  ["verb", "shine", "glimmer, glow, shine, gleam, blaze, dazzle"],
  ["verb", "flow", "drip, trickle, flow, stream, pour, gush, flood"],
  ["verb", "give off a smell", "smell, stink, reek"],
  ["verb", "take unlawfully", "pinch, pilfer, steal, rob, loot, plunder"],
  ["verb", "defeat", "edge, beat, defeat, trounce, crush"],
  ["verb", "not succeed", "falter, stumble, fail, flop, collapse"],
  ["verb", "make an effort", "try, endeavor, strive, struggle"],
  ["verb", "work hard", "work, labor, toil, slave"],
  ["verb", "hold back", "slow, hinder, impede, obstruct, block, thwart"],
  ["verb", "disallow", "discourage, restrict, forbid, prohibit, ban, outlaw"],
  ["verb", "have power over", "influence, guide, control, dominate, subjugate"],

  // ── Verbs: change and amount ─────────────────────────────────────────────
  ["verb", "make better", "tweak, refine, improve, enhance, transform, revolutionize"],
  ["verb", "make different", "tweak, adjust, modify, change, transform, overhaul"],
  ["verb", "go up", "rise, increase, climb, jump, surge, soar, skyrocket"],
  ["verb", "go down in amount", "dip, decrease, fall, drop, plunge, plummet, crash"],
  ["verb", "make smaller", "trim, reduce, cut, slash, gut"],
  ["verb", "get bigger", "grow, expand, swell, balloon, explode"],

  // ── Nouns: feelings ──────────────────────────────────────────────────────
  ["noun", "aversion", "distaste, dislike, aversion, hatred, loathing, revulsion"],
  ["noun", "affection", "liking, fondness, affection, love, passion, adoration, obsession"],
  ["noun", "anger", "annoyance, irritation, anger, outrage, fury, rage"],
  ["noun", "fear", "unease, apprehension, fear, dread, terror, horror"],
  ["noun", "worry", "concern, worry, anxiety, distress, anguish"],
  ["noun", "sadness", "disappointment, sadness, sorrow, grief, despair, anguish"],
  ["noun", "happiness", "contentment, happiness, joy, delight, elation, euphoria, ecstasy"],
  ["noun", "surprise", "surprise, amazement, astonishment, awe"],
  ["noun", "interest", "curiosity, interest, fascination, enthusiasm, passion, obsession"],
  ["noun", "excitement", "eagerness, excitement, enthusiasm, thrill, exhilaration, frenzy"],
  ["noun", "desire", "whim, wish, desire, longing, craving, lust"],
  ["noun", "hunger", "appetite, hunger, craving, starvation"],
  ["noun", "tiredness", "tiredness, fatigue, weariness, exhaustion, burnout"],
  ["noun", "pain", "twinge, discomfort, ache, pain, agony, torment"],
  ["noun", "pride", "satisfaction, pride, vanity, arrogance, hubris"],
  ["noun", "courage", "nerve, courage, bravery, valor, heroism"],
  ["noun", "shame", "awkwardness, embarrassment, shame, humiliation, disgrace"],
  ["noun", "guilt", "qualm, regret, guilt, remorse"],
  ["noun", "disgust", "distaste, disgust, repugnance, revulsion"],
  ["noun", "doubt", "question, uncertainty, doubt, skepticism, distrust, disbelief"],
  ["noun", "belief", "hunch, notion, belief, conviction, certainty"],
  ["noun", "esteem", "regard, respect, admiration, reverence, veneration"],

  // ── Nouns: things that go wrong ──────────────────────────────────────────
  ["noun", "problem", "hiccup, snag, issue, problem, crisis"],
  ["noun", "calamity", "mishap, setback, disaster, catastrophe, cataclysm"],
  ["noun", "mistake", "slip, lapse, error, mistake, blunder, fiasco"],
  ["noun", "failure", "setback, failure, flop, debacle"],
  ["noun", "hardship", "inconvenience, challenge, difficulty, hardship, ordeal, nightmare"],
  ["noun", "danger", "risk, hazard, danger, threat, peril"],
  ["noun", "flaw", "quirk, blemish, flaw, defect"],
  ["noun", "damage", "scratch, dent, damage, destruction, devastation"],
  ["noun", "wrongdoing", "infraction, offense, misdemeanor, crime, felony, atrocity"],
  ["noun", "falsehood", "exaggeration, fib, lie, deception, fraud"],
  ["noun", "disorder", "clutter, mess, disarray, chaos, pandemonium"],
  ["noun", "fall in amount", "dip, decline, drop, slump, plunge, crash, collapse"],

  // ── Nouns: people and conflict ───────────────────────────────────────────
  ["noun", "friend", "acquaintance, friend, companion, confidant, soulmate"],
  ["noun", "opponent", "competitor, rival, opponent, adversary, enemy, nemesis"],
  ["noun", "argument", "disagreement, tiff, squabble, argument, quarrel, fight, brawl"],
  ["noun", "armed conflict", "scuffle, skirmish, clash, battle, war"],
  ["noun", "attack", "jab, strike, attack, assault, onslaught"],
  ["noun", "insult", "dig, slight, insult, affront"],
  ["noun", "criticism", "feedback, critique, criticism, condemnation, denunciation"],
  ["noun", "praise", "approval, compliment, praise, acclaim, adulation"],
  ["noun", "request", "hint, suggestion, request, appeal, plea"],
  ["noun", "demand", "request, demand, ultimatum"],
  ["noun", "group of people", "cluster, group, crowd, throng, horde"],

  // ── Nouns: achievement and change ────────────────────────────────────────
  ["noun", "success", "progress, success, achievement, triumph"],
  ["noun", "ability", "aptitude, competence, skill, expertise, mastery, genius"],
  ["noun", "rise in amount", "uptick, increase, growth, surge, boom, explosion"],
  ["noun", "change", "tweak, adjustment, change, shift, transformation, revolution"],

  // ── Nouns: the physical world ────────────────────────────────────────────
  ["noun", "rain", "drizzle, shower, rain, downpour, deluge"],
  ["noun", "wind", "breeze, wind, gust, gale, storm, hurricane"],
  ["noun", "water", "drip, trickle, stream, torrent, flood"],
  ["noun", "waterway", "brook, creek, stream, river"],
  ["noun", "wave", "ripple, wave, breaker, tsunami"],
  ["noun", "fire", "spark, flame, fire, blaze, inferno"],
  ["noun", "light", "glimmer, glow, light, radiance, brilliance, glare"],
  ["noun", "sound", "murmur, sound, noise, racket, din, uproar"],
  ["noun", "smell", "whiff, scent, smell, odor, stench"],
  ["noun", "laughter", "titter, chuckle, laugh, guffaw, hysterics"],
  ["noun", "meal", "bite, snack, meal, feast, banquet"],
  ["noun", "dwelling", "shack, hut, cottage, house, mansion, palace"],
  ["noun", "settlement", "hamlet, village, town, city, metropolis"],
  ["noun", "landform", "mound, knoll, hill, peak, mountain"],
];
