// Intensity scales for nouns, verbs, adjectives and adverbs.
//
// Each entry is [partOfSpeech, sense, words], where `words` runs from the
// weakest word to the strongest. A word may appear in several scales when it
// has several senses (e.g. "worry" as a verb and as a noun).
//
// Rankings are judgement calls, not ground truth. Keep each scale to one
// meaning so that every step reads as "the same idea, but more (or less)".

export const SCALES = [
  // ── Verbs: feelings ──────────────────────────────────────────────────────
  ["verb", "feel aversion", "mind, dislike, hate, despise, detest, loathe, abhor"],
  ["verb", "feel affection", "like, fancy, love, adore, worship, idolize"],
  ["verb", "take pleasure in", "appreciate, enjoy, relish, savor, revel in"],
  ["verb", "want", "wish, want, desire, long, crave, yearn, lust"],
  ["verb", "be anxious", "wonder, worry, fret, agonize, obsess"],
  ["verb", "be afraid of", "worry, fear, dread"],
  ["verb", "be angry", "bristle, simmer, fume, seethe, rage"],
  ["verb", "hold in esteem", "respect, admire, revere, venerate, worship"],
  ["verb", "hold dear", "appreciate, value, cherish, treasure"],
  ["verb", "envy", "admire, envy, covet"],
  ["verb", "doubt", "question, doubt, distrust, disbelieve"],
  ["verb", "hold as true", "guess, suppose, think, believe, know"],
  ["verb", "understand", "follow, grasp, understand, comprehend, master"],
  ["verb", "think about", "consider, mull, ponder, contemplate, ruminate"],
  ["verb", "pay attention", "notice, heed, focus, concentrate, fixate"],
  ["verb", "grieve", "miss, pine, mourn, grieve"],
  ["verb", "feel sorry", "regret, rue, lament"],
  ["verb", "feel pain", "ache, hurt, suffer, agonize"],
  ["verb", "put up with", "accept, tolerate, bear, endure"],
  ["verb", "forgive", "excuse, forgive, pardon, absolve"],
  ["verb", "hold responsible", "suspect, blame, accuse, condemn"],

  // ── Verbs: affecting someone's feelings ──────────────────────────────────
  ["verb", "make angry", "bother, annoy, irritate, anger, infuriate, enrage"],
  ["verb", "make afraid", "unsettle, unnerve, alarm, scare, frighten, terrify, petrify"],
  ["verb", "make happy", "satisfy, please, delight, thrill, elate"],
  ["verb", "make sad", "disappoint, sadden, upset, distress, devastate"],
  ["verb", "catch off guard", "surprise, amaze, astonish, astound, stun, flabbergast"],
  ["verb", "make ashamed", "fluster, embarrass, shame, humiliate, mortify"],
  ["verb", "make unsure", "puzzle, confuse, perplex, baffle, bewilder"],
  ["verb", "arouse interest", "interest, intrigue, excite, thrill, electrify"],
  ["verb", "spur on", "encourage, motivate, inspire, energize, galvanize"],
  ["verb", "wear out", "tire, fatigue, weary, exhaust, drain"],
  ["verb", "give offense", "miff, offend, insult, outrage, scandalize"],
  ["verb", "repel", "displease, repel, disgust, sicken, revolt"],
  ["verb", "make anxious", "concern, trouble, worry, distress, torment"],
  ["verb", "attract", "interest, attract, charm, captivate, enchant, bewitch"],
  ["verb", "impress", "impress, wow, dazzle, awe"],
  ["verb", "keep bothering", "nag, pester, badger, hound, harass"],
  ["verb", "weigh on", "trouble, burden, strain, overwhelm, crush"],
  ["verb", "dishearten", "discourage, dishearten, demoralize, crush"],
  ["verb", "make calm", "settle, soothe, calm, pacify"],

  // ── Verbs: speaking and reacting ─────────────────────────────────────────
  ["verb", "say aloud", "whisper, murmur, say, exclaim, shout, yell, scream"],
  ["verb", "cry", "sniffle, whimper, cry, weep, sob, bawl, wail"],
  ["verb", "laugh", "chuckle, giggle, laugh, cackle, guffaw, howl"],
  ["verb", "smile", "smirk, smile, grin, beam"],
  ["verb", "ask for", "ask, request, urge, plead, beg, implore"],
  ["verb", "propose", "suggest, recommend, advise, urge, insist, demand"],
  ["verb", "give orders", "instruct, direct, order, command, decree"],
  ["verb", "disagree", "disagree, bicker, argue, quarrel, fight, feud"],
  ["verb", "find fault", "question, critique, criticize, condemn, denounce, excoriate"],
  ["verb", "tell off", "chide, scold, reprimand, rebuke, berate, lambaste"],
  ["verb", "speak well of", "compliment, commend, praise, acclaim, extol, glorify"],
  ["verb", "express discontent", "grumble, complain, protest, rail, rant"],
  ["verb", "make fun of", "tease, taunt, mock, ridicule, deride"],
  ["verb", "caution", "remind, caution, warn, threaten"],
  ["verb", "persuade", "nudge, encourage, persuade, pressure, coerce, force"],
  ["verb", "back", "tolerate, accept, support, endorse, champion"],
  ["verb", "turn down", "decline, refuse, reject, rebuff, spurn"],
  ["verb", "pay no attention", "overlook, disregard, ignore, snub, shun, ostracize"],
  ["verb", "mislead", "fudge, fib, mislead, lie, deceive, defraud"],
  ["verb", "make known", "hint, mention, state, announce, declare, proclaim"],
  ["verb", "state as true", "imply, suggest, claim, assert, insist"],
  ["verb", "own up", "acknowledge, admit, confess"],
  ["verb", "say is untrue", "question, dispute, deny, refute, repudiate"],
  ["verb", "promise", "offer, promise, pledge, vow, swear"],
  ["verb", "ask questions", "ask, query, question, interrogate, grill"],
  ["verb", "insult", "needle, slight, insult, disparage, vilify"],
  ["verb", "intimidate", "pressure, intimidate, bully, menace, terrorize"],
  ["verb", "try to please", "flatter, fawn, grovel"],
  ["verb", "reveal", "hint, reveal, disclose, expose"],
  ["verb", "hide", "mask, hide, conceal, bury"],
  ["verb", "expect of someone", "ask, expect, require, demand"],
  ["verb", "welcome", "accept, welcome, embrace"],
  ["verb", "keep out", "exclude, bar, ban, banish, exile"],
  ["verb", "moan", "sigh, moan, groan, howl"],
  ["verb", "look displeased", "pout, frown, scowl, glower, glare"],
  ["verb", "show to be true", "suggest, indicate, show, demonstrate, prove"],
  ["verb", "oppose", "question, challenge, oppose, resist, fight"],
  ["verb", "startle", "surprise, startle, shock, stun, traumatize"],
  ["verb", "applaud", "clap, applaud, cheer, roar"],

  // ── Verbs: moving and acting ─────────────────────────────────────────────
  ["verb", "go on foot", "amble, stroll, walk, stride, march"],
  ["verb", "run", "jog, trot, run, race, sprint"],
  ["verb", "go down", "slip, stumble, fall, tumble, plunge, plummet"],
  ["verb", "eat", "nibble, snack, eat, gobble, devour, gorge"],
  ["verb", "drink", "sip, drink, gulp, guzzle, chug"],
  ["verb", "look", "peek, glance, look, gaze, stare, gawk"],
  ["verb", "look over", "check, review, examine, inspect, scrutinize"],
  ["verb", "read", "skim, browse, read, study, pore over"],
  ["verb", "sleep", "doze, nap, sleep, slumber"],
  ["verb", "hold", "hold, grip, grasp, clutch, clench"],
  ["verb", "take hold of", "take, grab, snatch, seize"],
  ["verb", "hit", "tap, knock, hit, strike, whack, smash, pummel"],
  ["verb", "push", "nudge, push, shove, thrust, ram"],
  ["verb", "pull", "tug, pull, yank, wrench"],
  ["verb", "throw", "toss, throw, fling, hurl"],
  ["verb", "press together", "press, squeeze, squash, crush"],
  ["verb", "cut", "nick, scratch, cut, gash, slash, sever"],
  ["verb", "break", "chip, crack, break, shatter, smash, pulverize"],
  ["verb", "damage", "damage, ruin, wreck, destroy, devastate, annihilate, obliterate"],
  ["verb", "injure", "sting, harm, hurt, injure, wound, maim"],
  ["verb", "kill", "kill, murder, slay, slaughter, massacre, exterminate"],
  ["verb", "burn", "singe, scorch, burn, char, incinerate"],
  ["verb", "clean", "wipe, rinse, clean, wash, scrub, scour"],
  ["verb", "shake", "quiver, tremble, shake, shudder, convulse"],
  ["verb", "shine", "flicker, glimmer, glow, shine, gleam, blaze, dazzle"],
  ["verb", "flow", "drip, trickle, flow, stream, pour, gush, flood"],
  ["verb", "give off a smell", "smell, stink, reek"],
  ["verb", "take unlawfully", "pinch, pilfer, steal, rob, loot, plunder"],
  ["verb", "defeat", "edge, beat, defeat, trounce, crush"],
  ["verb", "not succeed", "falter, stumble, fail, flop, collapse"],
  ["verb", "make an effort", "try, endeavor, strive, struggle"],
  ["verb", "work hard", "work, labor, toil, slave"],
  ["verb", "hold back", "slow, hinder, impede, obstruct, block, thwart"],
  ["verb", "disallow", "discourage, restrict, forbid, prohibit, ban, outlaw"],
  ["verb", "have power over", "influence, guide, control, dominate, subjugate"],
  ["verb", "move quickly", "hurry, rush, dash, bolt"],
  ["verb", "help", "assist, help, rescue"],
  ["verb", "need", "prefer, want, need, require"],
  ["verb", "slap", "pat, slap, smack, wallop"],
  ["verb", "carry with effort", "carry, lug, haul, drag"],
  ["verb", "bend", "flex, bend, twist, contort, mangle"],
  ["verb", "make dry", "dry, parch, dehydrate, desiccate"],
  ["verb", "sparkle", "twinkle, glint, sparkle, glitter, dazzle"],
  ["verb", "jump", "hop, jump, leap, bound"],
  ["verb", "touch", "graze, brush, touch, press"],
  ["verb", "poke", "tap, poke, prod, jab, stab"],
  ["verb", "bite", "nibble, nip, bite, chomp"],
  ["verb", "tear", "snag, tear, rip, shred"],
  ["verb", "turn around", "turn, rotate, spin, whirl"],
  ["verb", "move arms about", "wave, flap, flail, thrash"],
  ["verb", "breathe hard", "breathe, puff, pant, gasp, wheeze"],
  ["verb", "make hot", "warm, heat, boil, scald"],
  ["verb", "make cold", "cool, chill, freeze"],
  ["verb", "make wet", "moisten, dampen, wet, soak, drench"],
  ["verb", "fill", "fill, pack, stuff, cram, jam"],
  ["verb", "rain", "spit, drizzle, rain, pour"],
  ["verb", "make a deep sound", "hum, rumble, roar, thunder"],
  ["verb", "go bad", "spoil, sour, rot, putrefy"],
  ["verb", "make impure", "taint, pollute, contaminate, poison"],
  ["verb", "stop", "pause, suspend, stop, halt, end, terminate"],
  ["verb", "get away", "leave, withdraw, retreat, flee, escape"],
  ["verb", "go after", "follow, trail, pursue, chase, hunt"],
  ["verb", "search", "look, search, hunt, rummage, comb, scour"],
  ["verb", "attack", "harass, attack, assault, ravage"],
  ["verb", "fight physically", "spar, scuffle, fight, brawl"],
  ["verb", "treat harshly", "restrict, repress, oppress, persecute, crush"],
  ["verb", "mistreat", "neglect, mistreat, abuse, torment, torture"],
  ["verb", "leave behind", "neglect, leave, abandon, desert"],
  ["verb", "take advantage of", "use, exploit, milk, abuse"],
  ["verb", "use up", "use, spend, consume, deplete, exhaust"],
  ["verb", "waste", "misspend, fritter, waste, squander"],
  ["verb", "fix", "patch, mend, fix, repair, restore, rebuild"],
  ["verb", "succeed", "manage, succeed, excel, triumph"],
  ["verb", "do well", "survive, cope, thrive, flourish, boom"],

  // ── Verbs: change and amount ─────────────────────────────────────────────
  ["verb", "make better", "tweak, refine, improve, enhance, transform, revolutionize"],
  ["verb", "make different", "tweak, adjust, alter, modify, change, transform, overhaul"],
  ["verb", "go up", "rise, increase, climb, jump, surge, soar, skyrocket"],
  ["verb", "go down in amount", "dip, decrease, fall, drop, plunge, plummet, crash"],
  ["verb", "make smaller", "trim, reduce, cut, slash, gut"],
  ["verb", "get bigger", "grow, expand, swell, balloon, explode"],
  ["verb", "get smaller", "contract, shrink, dwindle, shrivel, vanish"],
  ["verb", "increase in number", "grow, multiply, proliferate, explode"],
  ["verb", "fade", "wane, fade, dwindle, vanish"],
  ["verb", "get worse", "slip, decline, worsen, deteriorate, crumble, collapse"],
  ["verb", "make worse", "complicate, worsen, aggravate, exacerbate"],
  ["verb", "weaken", "soften, weaken, undermine, sap, cripple"],
  ["verb", "strengthen", "bolster, strengthen, reinforce, fortify"],
  ["verb", "get rid of", "reduce, remove, eliminate, eradicate"],

  // ── Nouns: feelings ──────────────────────────────────────────────────────
  ["noun", "aversion", "distaste, dislike, aversion, hatred, loathing, revulsion"],
  ["noun", "affection", "liking, fondness, affection, love, passion, adoration, obsession"],
  ["noun", "anger", "annoyance, irritation, anger, outrage, fury, rage"],
  ["noun", "fear", "unease, apprehension, fear, dread, terror, horror"],
  ["noun", "worry", "concern, worry, anxiety, distress, anguish"],
  ["noun", "sadness", "disappointment, sadness, sorrow, grief, despair, anguish"],
  ["noun", "happiness", "contentment, happiness, joy, delight, elation, euphoria, ecstasy"],
  ["noun", "surprise", "surprise, amazement, astonishment, awe"],
  ["noun", "interest", "curiosity, interest, fascination, enthusiasm, passion, obsession"],
  ["noun", "excitement", "eagerness, excitement, enthusiasm, thrill, exhilaration, frenzy"],
  ["noun", "desire", "whim, wish, desire, longing, craving, lust"],
  ["noun", "hunger", "appetite, hunger, craving, starvation"],
  ["noun", "tiredness", "tiredness, fatigue, weariness, exhaustion, burnout"],
  ["noun", "pain", "twinge, discomfort, ache, pain, agony, torment"],
  ["noun", "pride", "satisfaction, pride, vanity, arrogance, hubris"],
  ["noun", "courage", "nerve, courage, bravery, valor, heroism"],
  ["noun", "shame", "awkwardness, embarrassment, shame, humiliation, disgrace"],
  ["noun", "guilt", "qualm, regret, guilt, remorse"],
  ["noun", "disgust", "distaste, disgust, repugnance, revulsion"],
  ["noun", "doubt", "question, uncertainty, doubt, skepticism, distrust, disbelief"],
  ["noun", "belief", "hunch, notion, opinion, belief, conviction, certainty"],
  ["noun", "esteem", "regard, respect, admiration, reverence, veneration"],
  ["noun", "calm", "calm, peace, serenity, tranquility"],
  ["noun", "resentment", "pique, resentment, bitterness, rancor, spite"],
  ["noun", "contempt", "disregard, disdain, scorn, contempt"],
  ["noun", "confusion", "puzzlement, confusion, perplexity, bewilderment"],
  ["noun", "loneliness", "solitude, loneliness, isolation, desolation"],
  ["noun", "stress", "tension, pressure, stress, strain"],
  ["noun", "panic", "nervousness, panic, hysteria"],
  ["noun", "trust", "reliance, trust, faith, devotion"],
  ["noun", "cruelty", "unkindness, meanness, cruelty, brutality, savagery"],
  ["noun", "thirst", "dryness, thirst, dehydration"],
  ["noun", "shock", "surprise, jolt, shock, trauma"],
  ["noun", "pleasure", "satisfaction, enjoyment, pleasure, delight, bliss"],
  ["noun", "suffering", "discomfort, hardship, suffering, misery, torment"],
  ["noun", "frustration", "annoyance, frustration, exasperation, despair"],
  ["noun", "boredom", "restlessness, boredom, tedium"],
  ["noun", "attention", "notice, attention, focus, fixation, obsession"],
  ["noun", "knowledge", "awareness, familiarity, knowledge, expertise, mastery"],
  ["noun", "need", "preference, desire, need, necessity"],

  // ── Nouns: things that go wrong ──────────────────────────────────────────
  ["noun", "problem", "hiccup, snag, issue, problem, crisis"],
  ["noun", "calamity", "mishap, setback, disaster, catastrophe, cataclysm"],
  ["noun", "mistake", "slip, lapse, error, mistake, blunder, fiasco"],
  ["noun", "failure", "setback, failure, flop, debacle"],
  ["noun", "hardship", "inconvenience, challenge, difficulty, hardship, ordeal, nightmare"],
  ["noun", "danger", "risk, hazard, danger, threat, peril"],
  ["noun", "flaw", "quirk, blemish, flaw, fault, defect"],
  ["noun", "damage", "scratch, dent, damage, destruction, devastation"],
  ["noun", "wrongdoing", "infraction, offense, misdemeanor, crime, felony, atrocity"],
  ["noun", "falsehood", "exaggeration, fib, lie, deception, fraud"],
  ["noun", "disorder", "clutter, mess, disarray, chaos, pandemonium"],
  ["noun", "fall in amount", "dip, decline, drop, slump, plunge, crash, collapse"],
  ["noun", "delay", "pause, lag, delay, holdup, standstill"],
  ["noun", "malfunction", "glitch, fault, malfunction, failure, breakdown"],
  ["noun", "difference", "nuance, distinction, difference, gap, gulf, chasm"],
  ["noun", "obstacle", "hitch, hurdle, obstacle, barrier"],
  ["noun", "illness", "sniffle, bug, illness, disease"],
  ["noun", "outbreak", "case, cluster, outbreak, epidemic, pandemic"],
  ["noun", "injury", "scrape, bruise, injury, wound, trauma"],
  ["noun", "defeat", "setback, loss, defeat, rout, drubbing"],
  ["noun", "violence", "unrest, violence, bloodshed, carnage, massacre"],
  ["noun", "dirt", "speck, smudge, dirt, grime, filth"],
  ["noun", "lack of money", "thrift, hardship, poverty, destitution"],
  ["noun", "shortage", "shortfall, shortage, scarcity, dearth"],
  ["noun", "trick", "prank, trick, ruse, con, scam, swindle"],
  ["noun", "theft", "pilfering, theft, robbery, heist"],
  ["noun", "punishment", "warning, reprimand, penalty, punishment, retribution"],
  ["noun", "complaint", "quibble, gripe, complaint, protest, outcry"],
  ["noun", "warning", "reminder, caution, warning, alarm"],

  // ── Nouns: people and conflict ───────────────────────────────────────────
  ["noun", "friend", "acquaintance, friend, companion, confidant, soulmate"],
  ["noun", "opponent", "competitor, rival, opponent, adversary, enemy, nemesis"],
  ["noun", "argument", "disagreement, tiff, squabble, argument, quarrel, fight, brawl"],
  ["noun", "armed conflict", "scuffle, skirmish, clash, conflict, battle, war"],
  ["noun", "attack", "jab, strike, attack, assault, onslaught"],
  ["noun", "insult", "dig, slight, insult, affront"],
  ["noun", "criticism", "feedback, critique, criticism, condemnation, denunciation"],
  ["noun", "praise", "approval, compliment, praise, acclaim, adulation"],
  ["noun", "request", "hint, suggestion, request, appeal, plea"],
  ["noun", "demand", "request, demand, ultimatum"],
  ["noun", "group of people", "cluster, group, crowd, throng, mob, horde"],
  ["noun", "fan", "admirer, fan, enthusiast, devotee, fanatic"],
  ["noun", "supporter", "sympathizer, supporter, backer, advocate, champion"],
  ["noun", "ruler", "leader, ruler, autocrat, dictator, tyrant"],
  ["noun", "skilled person", "novice, amateur, professional, expert, master, virtuoso"],
  ["noun", "famous person", "celebrity, star, superstar, megastar, legend"],
  ["noun", "wrongdoer", "rascal, offender, criminal, villain, monster"],
  ["noun", "fool", "goof, fool, idiot, imbecile"],
  ["noun", "uprising", "protest, demonstration, riot, uprising, revolution"],
  ["noun", "promise", "assurance, promise, pledge, vow, oath"],
  ["noun", "order", "instruction, direction, order, command, decree"],
  ["noun", "evidence", "hint, clue, indication, evidence, proof"],

  // ── Nouns: achievement and change ────────────────────────────────────────
  ["noun", "success", "progress, success, achievement, triumph"],
  ["noun", "ability", "aptitude, competence, skill, expertise, mastery, genius"],
  ["noun", "rise in amount", "uptick, increase, growth, surge, boom, explosion"],
  ["noun", "change", "tweak, adjustment, change, shift, transformation, revolution"],
  ["noun", "improvement", "tweak, refinement, improvement, upgrade, overhaul"],
  ["noun", "victory", "win, victory, triumph"],
  ["noun", "effort", "try, attempt, effort, struggle, crusade"],
  ["noun", "hard work", "work, labor, toil, drudgery"],
  ["noun", "likelihood", "possibility, chance, likelihood, certainty"],
  ["noun", "fame", "recognition, renown, fame, stardom, immortality"],
  ["noun", "power", "sway, influence, clout, power, dominance, supremacy"],
  ["noun", "wealth", "comfort, prosperity, affluence, wealth, opulence"],
  ["noun", "large amount", "plenty, abundance, surplus, glut, flood"],
  ["noun", "gain", "gain, profit, windfall, bonanza, jackpot"],
  ["noun", "beauty", "charm, beauty, splendor, magnificence"],

  // ── Nouns: the physical world ────────────────────────────────────────────
  ["noun", "rain", "drizzle, shower, rain, downpour, deluge"],
  ["noun", "wind", "breeze, wind, gust, gale, storm, hurricane"],
  ["noun", "water", "drip, trickle, stream, torrent, flood"],
  ["noun", "waterway", "brook, creek, stream, river"],
  ["noun", "wave", "ripple, wave, breaker, tsunami"],
  ["noun", "fire", "spark, flame, fire, blaze, inferno"],
  ["noun", "light", "glimmer, glow, light, radiance, brilliance, glare"],
  ["noun", "sound", "murmur, sound, noise, racket, din, uproar"],
  ["noun", "smell", "whiff, scent, smell, odor, stench"],
  ["noun", "laughter", "titter, chuckle, laugh, guffaw, hysterics"],
  ["noun", "meal", "bite, snack, meal, feast, banquet"],
  ["noun", "dwelling", "shack, hut, cottage, house, mansion, palace"],
  ["noun", "settlement", "hamlet, village, town, city, metropolis"],
  ["noun", "landform", "mound, knoll, hill, peak, mountain"],
  ["noun", "snow", "flurry, snow, snowstorm, blizzard"],
  ["noun", "cold", "coolness, chill, cold, frost"],
  ["noun", "silence", "lull, quiet, hush, silence"],
  ["noun", "pile", "stack, pile, heap, mountain"],
  ["noun", "hole", "pit, hole, crater, chasm, abyss"],
  ["noun", "body of water", "puddle, pond, lake, sea, ocean"],
  ["noun", "group of trees", "copse, grove, wood, forest"],
  ["noun", "piece", "crumb, bit, piece, chunk, slab"],
  ["noun", "blow", "tap, knock, blow, punch, wallop"],
  ["noun", "explosion", "pop, bang, blast, explosion"],
  ["noun", "party", "get-together, gathering, party, celebration, extravaganza"],
  ["noun", "sum of money", "pittance, sum, bundle, fortune"],
  ["noun", "journey", "outing, trip, journey, voyage, odyssey"],
  ["noun", "walk", "stroll, walk, hike, trek"],
  ["noun", "look", "glimpse, glance, look, gaze, stare, glare"],
  ["noun", "cry", "whimper, cry, wail, scream, shriek"],

  // ── Adjectives: feelings ─────────────────────────────────────────────────
  ["adjective", "happy", "content, pleased, happy, delighted, thrilled, ecstatic"],
  ["adjective", "sad", "down, unhappy, sad, miserable, heartbroken, devastated"],
  ["adjective", "angry", "irritated, annoyed, cross, angry, furious, livid"],
  ["adjective", "afraid", "uneasy, nervous, afraid, scared, frightened, terrified, petrified"],
  ["adjective", "worried", "concerned, worried, anxious, distressed, distraught, frantic"],
  ["adjective", "stressed", "tense, stressed, frazzled, overwhelmed"],
  ["adjective", "calm", "composed, calm, peaceful, serene"],
  ["adjective", "excited", "keen, eager, excited, thrilled, elated"],
  ["adjective", "surprised", "surprised, amazed, astonished, astounded, stunned, flabbergasted"],
  ["adjective", "embarrassed", "awkward, embarrassed, ashamed, humiliated, mortified"],
  ["adjective", "confused", "unsure, puzzled, confused, baffled, bewildered"],
  ["adjective", "tired", "tired, weary, exhausted, drained"],
  ["adjective", "hungry", "peckish, hungry, famished, ravenous, starving"],
  ["adjective", "thirsty", "thirsty, parched, dehydrated"],
  ["adjective", "lonely", "solitary, lonely, isolated, forlorn, desolate"],
  ["adjective", "hopeful", "hopeful, optimistic, confident"],
  ["adjective", "hopeless", "discouraged, gloomy, despondent, hopeless, desperate"],
  ["adjective", "jealous", "envious, jealous, resentful, bitter"],
  ["adjective", "proud", "satisfied, proud, smug, conceited, arrogant"],
  ["adjective", "self-assured", "assured, confident, bold, brash, cocky"],
  ["adjective", "willing", "open, willing, keen, eager, desperate"],
  ["adjective", "unwilling", "hesitant, reluctant, unwilling, resistant, opposed"],
  ["adjective", "sure", "hopeful, confident, sure, certain, positive"],
  ["adjective", "curious", "curious, inquisitive, nosy"],
  ["adjective", "drunk", "tipsy, drunk, hammered"],

  // ── Adjectives: people and behavior ──────────────────────────────────────
  ["adjective", "kind", "decent, kind, generous, selfless, saintly"],
  ["adjective", "unkind", "unkind, mean, nasty, cruel, vicious, sadistic"],
  ["adjective", "friendly", "civil, cordial, friendly, warm, affectionate"],
  ["adjective", "unfriendly", "aloof, unfriendly, hostile, aggressive, belligerent"],
  ["adjective", "rude", "curt, impolite, rude, insolent, offensive"],
  ["adjective", "brave", "bold, brave, courageous, fearless, heroic"],
  ["adjective", "strict", "firm, strict, stern, harsh, draconian"],
  ["adjective", "violent", "rough, aggressive, violent, brutal, savage"],
  ["adjective", "wicked", "naughty, wicked, evil, monstrous, diabolical"],
  ["adjective", "loyal", "faithful, loyal, devoted, fanatical"],
  ["adjective", "outspoken", "frank, candid, direct, blunt"],
  ["adjective", "careful", "attentive, careful, thorough, meticulous, painstaking"],
  ["adjective", "careless", "hasty, careless, sloppy, negligent, reckless"],
  ["adjective", "lazy", "idle, lazy, slothful"],
  ["adjective", "talkative", "chatty, talkative, garrulous, loquacious"],
  ["adjective", "free-spending", "generous, lavish, extravagant"],
  ["adjective", "stingy", "thrifty, frugal, stingy, miserly"],
  ["adjective", "greedy", "materialistic, greedy, grasping, rapacious"],
  ["adjective", "intelligent", "bright, smart, clever, intelligent, brilliant"],
  ["adjective", "foolish", "unwise, silly, foolish, stupid, idiotic"],
  ["adjective", "skilled", "competent, capable, skilled, accomplished, masterful"],
  ["adjective", "famous", "known, well-known, famous, renowned, legendary"],
  ["adjective", "rich", "well-off, rich, wealthy, affluent"],
  ["adjective", "poor", "hard-up, poor, impoverished, destitute"],
  ["adjective", "busy", "occupied, busy, hectic, frantic"],

  // ── Adjectives: quality and importance ───────────────────────────────────
  ["adjective", "good", "adequate, decent, good, great, excellent, superb, outstanding"],
  ["adjective", "bad", "mediocre, poor, bad, terrible, awful, abysmal"],
  ["adjective", "morally good", "decent, good, virtuous, saintly, angelic"],
  ["adjective", "pleasant", "pleasant, nice, lovely, delightful, wonderful"],
  ["adjective", "unpleasant", "unpleasant, nasty, horrible, vile, repulsive"],
  ["adjective", "impressive", "impressive, remarkable, amazing, astonishing, incredible, phenomenal"],
  ["adjective", "beautiful", "attractive, pretty, beautiful, gorgeous, stunning"],
  ["adjective", "ugly", "plain, unattractive, ugly, hideous, grotesque"],
  ["adjective", "cute", "sweet, cute, adorable"],
  ["adjective", "interesting", "interesting, intriguing, fascinating, captivating, riveting"],
  ["adjective", "boring", "bland, dull, boring, tedious, mind-numbing"],
  ["adjective", "funny", "droll, amusing, funny, hilarious, hysterical"],
  ["adjective", "exciting", "stimulating, exciting, thrilling, exhilarating, electrifying"],
  ["adjective", "annoying", "bothersome, annoying, irritating, infuriating, maddening"],
  ["adjective", "frightening", "unnerving, alarming, scary, frightening, terrifying"],
  ["adjective", "upsetting", "disappointing, upsetting, distressing, heartbreaking, devastating"],
  ["adjective", "shocking", "surprising, startling, shocking, appalling, horrifying"],
  ["adjective", "disgusting", "unappealing, distasteful, disgusting, revolting, repulsive"],
  ["adjective", "tiring", "tiring, draining, exhausting, grueling, punishing"],
  ["adjective", "important", "relevant, important, significant, crucial, vital"],
  ["adjective", "unimportant", "minor, trivial, insignificant, negligible"],
  ["adjective", "necessary", "useful, necessary, essential, indispensable"],
  ["adjective", "valuable", "worthwhile, valuable, precious, priceless"],
  ["adjective", "urgent", "timely, pressing, urgent, critical"],
  ["adjective", "serious", "concerning, serious, severe, grave, dire"],
  ["adjective", "harmful", "unhealthy, harmful, damaging, destructive, devastating"],
  ["adjective", "dangerous", "risky, hazardous, dangerous, perilous, deadly"],
  ["adjective", "easy", "manageable, easy, effortless"],
  ["adjective", "difficult", "tricky, hard, difficult, arduous, grueling"],
  ["adjective", "complicated", "involved, complicated, complex, intricate, convoluted"],
  ["adjective", "strange", "unusual, odd, strange, weird, bizarre"],
  ["adjective", "rare", "uncommon, rare, scarce"],
  ["adjective", "common", "frequent, common, widespread, pervasive, ubiquitous"],
  ["adjective", "likely", "possible, plausible, likely, probable, certain"],
  ["adjective", "obvious", "noticeable, apparent, clear, obvious, glaring, blatant"],
  ["adjective", "marked", "slight, noticeable, marked, dramatic, drastic"],
  ["adjective", "complete", "partial, substantial, complete, total, utter"],
  ["adjective", "exact", "rough, close, accurate, precise, exact"],
  ["adjective", "intense", "mild, moderate, strong, intense, overpowering"],
  ["adjective", "expensive", "pricey, expensive, costly, exorbitant"],
  ["adjective", "cheap", "reasonable, affordable, cheap, dirt-cheap"],
  ["adjective", "luxurious", "comfortable, plush, luxurious, opulent"],
  ["adjective", "clean", "tidy, clean, spotless, immaculate, pristine"],
  ["adjective", "dirty", "grubby, dirty, grimy, filthy, squalid"],
  ["adjective", "messy", "cluttered, untidy, messy, chaotic"],
  ["adjective", "crowded", "busy, crowded, packed, overcrowded"],
  ["adjective", "healthy", "healthy, fit, robust"],
  ["adjective", "painful", "tender, sore, painful, agonizing, excruciating"],
  ["adjective", "tasty", "palatable, tasty, delicious, scrumptious"],
  ["adjective", "smelly", "musty, smelly, stinking, rank, putrid"],

  // ── Adjectives: size, amount and the physical world ──────────────────────
  ["adjective", "big", "sizable, large, big, huge, enormous, gigantic, colossal"],
  ["adjective", "small", "small, little, tiny, minuscule, microscopic"],
  ["adjective", "high up", "raised, high, lofty, towering"],
  ["adjective", "extensive", "wide, broad, vast, boundless"],
  ["adjective", "long in time", "long, lengthy, protracted, endless, interminable"],
  ["adjective", "short in time", "short, brief, fleeting, momentary"],
  ["adjective", "full", "full, packed, crammed, overflowing"],
  ["adjective", "empty", "sparse, empty, deserted, desolate"],
  ["adjective", "fat", "plump, chubby, fat, obese"],
  ["adjective", "thin", "slim, thin, skinny, gaunt, emaciated"],
  ["adjective", "strong", "sturdy, strong, powerful, mighty"],
  ["adjective", "weak", "weak, feeble, frail, helpless"],
  ["adjective", "hard to the touch", "firm, hard, rigid, rock-hard"],
  ["adjective", "fast", "brisk, quick, fast, rapid, breakneck"],
  ["adjective", "slow", "leisurely, slow, sluggish, glacial"],
  ["adjective", "loud", "audible, loud, noisy, booming, deafening"],
  ["adjective", "quiet", "soft, quiet, hushed, silent"],
  ["adjective", "bright", "bright, brilliant, dazzling, blinding"],
  ["adjective", "dark", "dim, dark, murky, pitch-black"],
  ["adjective", "shiny", "glossy, shiny, gleaming, sparkling, dazzling"],
  ["adjective", "hot", "lukewarm, warm, hot, boiling, scorching"],
  ["adjective", "cold", "cool, chilly, cold, freezing, frigid"],
  ["adjective", "wet", "damp, wet, soggy, soaked, drenched"],
  ["adjective", "dry", "dry, parched, arid"],
  ["adjective", "spicy", "spicy, hot, fiery"],
  ["adjective", "sweet", "sweet, sugary, cloying"],
  ["adjective", "windy", "breezy, windy, blustery, stormy, tempestuous"],
  ["adjective", "rainy", "drizzly, showery, rainy, torrential"],
  ["adjective", "cloudy", "hazy, cloudy, overcast, gloomy"],
  ["adjective", "steep", "sloping, steep, sheer, vertical"],

  // ── Adverbs: degree and intensity ────────────────────────────────────────
  ["adverb", "to a high degree", "somewhat, noticeably, considerably, substantially, greatly, immensely, exceedingly"],
  ["adverb", "to an extreme degree", "greatly, intensely, extremely, exceptionally, extraordinarily, astronomically"],
  ["adverb", "to a minimal degree", "scarcely, hardly, barely, slightly, somewhat"],
  ["adverb", "completely", "partly, largely, mostly, entirely, completely, totally, absolutely, utterly"],
  ["adverb", "moderately", "slightly, mildly, moderately, reasonably, fairly"],
  ["adverb", "excessively", "adequately, overly, excessively, immoderately, inordinately"],
  ["adverb", "noticeably", "faintly, visibly, noticeably, distinctly, conspicuously, glaringly"],
  ["adverb", "deeply", "mildly, moderately, deeply, profoundly, overwhelmingly"],
  ["adverb", "intensely", "mildly, moderately, strongly, intensely, fiercely, violently"],
  ["adverb", "partially", "slightly, partially, largely, fully"],

  // ── Adverbs: speed, time and frequency ───────────────────────────────────
  ["adverb", "quickly", "briskly, quickly, swiftly, rapidly, hastily, furiously"],
  ["adverb", "slowly", "unhurriedly, leisurely, slowly, sluggishly, gradually, glacially"],
  ["adverb", "instantly", "promptly, quickly, instantly, immediately, instantaneously"],
  ["adverb", "soon", "presently, shortly, soon, imminently"],
  ["adverb", "frequently", "seldom, occasionally, sometimes, often, frequently, regularly, constantly, always"],
  ["adverb", "infrequently", "sometimes, occasionally, rarely, seldom, never"],
  ["adverb", "continuously", "frequently, repeatedly, constantly, incessantly, perpetually, endlessly"],
  ["adverb", "suddenly", "unexpectedly, abruptly, suddenly, startlingly"],
  ["adverb", "gradually", "steadily, gradually, progressively, incrementally"],
  ["adverb", "early", "punctually, early, ahead of time"],
  ["adverb", "late", "belatedly, tardily, late"],
  ["adverb", "habitually", "often, usually, regularly, habitually, invariably"],
  ["adverb", "briefly", "fleetingly, briefly, temporarily, provisionally"],

  // ── Adverbs: manner and emotion ──────────────────────────────────────────
  ["adverb", "happily", "pleasantly, cheerfully, gladly, happily, joyfully, ecstatically, blissfully"],
  ["adverb", "sadly", "glumly, sadly, mournfully, sorrowfully, despondently, inconsolably"],
  ["adverb", "angrily", "crossly, irritably, angrily, furiously, wrathfully, murderously"],
  ["adverb", "fearfully", "uneasily, nervously, anxiously, fearfully, terrifiedly, hysterically"],
  ["adverb", "calmly", "mildly, quietly, calmly, serenely, placidly, imperturbably"],
  ["adverb", "gently", "lightly, softly, gently, tenderly, delicately"],
  ["adverb", "harshly", "firmly, sharply, sternly, harshly, severely, brutally, cruelly"],
  ["adverb", "eagerly", "willingly, gladly, eagerly, avidly, passionately, frantically"],
  ["adverb", "reluctantly", "hesitantly, begrudgingly, reluctantly, stubbornly, unwillingly"],
  ["adverb", "boldly", "confidently, bravely, boldly, daringly, recklessly, audaciously"],
  ["adverb", "timidly", "shyly, hesitantly, timidly, meekly, coweringly"],
  ["adverb", "warmly", "politely, kindly, cordially, warmly, affectionately, lovingly"],
  ["adverb", "coldly", "distantly, aloofly, coldly, frostily, icily"],
  ["adverb", "carefully", "mindfully, carefully, cautiously, thoroughly, meticulously, painstakingly"],
  ["adverb", "carelessly", "casually, hastily, carelessly, sloppily, recklessly, heedlessly"],
  ["adverb", "proudly", "satisfyingly, proudly, smugly, conceitedly, arrogantly, haughtily"],
  ["adverb", "rudely", "curtly, bluntly, impolitely, rudely, insolently, offensively"],
  ["adverb", "bravely", "firmly, boldly, bravely, courageously, valiantly, heroically"],
  ["adverb", "loudly", "audibly, aloud, loudly, noisily, deafeningly, thunderously"],
  ["adverb", "quietly", "faintly, softly, quietly, hushedly, silently, inaudibly"],
  ["adverb", "wildly", "freely, wildly, frantically, uncontrollably, maniacally"],
  ["adverb", "painfully", "uncomfortably, sorely, painfully, agonizingly, excruciatingly"],
  ["adverb", "sweetly", "pleasantly, nicely, sweetly, charmingly, delightfully"],

  // ── Adverbs: certainty, truth and openness ────────────────────────────────
  ["adverb", "certainly", "possibly, probably, likely, definitely, certainly, undeniably, absolutely"],
  ["adverb", "doubtfully", "questioningly, skeptically, suspiciously, doubtfully, incredulously"],
  ["adverb", "honestly", "frankly, honestly, candidly, truthfully, sincerely"],
  ["adverb", "secretly", "discreetly, quietly, secretly, stealthily, furtively, surreptitiously"],
  ["adverb", "openly", "publicly, openly, frankly, brazenly, unashamedly"],
  ["adverb", "clearly", "apparently, clearly, obviously, plainly, glaringly, blatantly"],
  ["adverb", "strictly", "firmly, strictly, rigidly, rigorously, uncompromisingly"],
  ["adverb", "vaguely", "hazily, vaguely, unclearly, indistinctly, imperceptibly"],

  // ── Adverbs: quality, ease and effort ────────────────────────────────────
  ["adverb", "well", "adequately, acceptably, well, nicely, skillfully, superbly, brilliantly"],
  ["adverb", "badly", "poorly, badly, terribly, horribly, dreadfully, appallingly, atrociously"],
  ["adverb", "easily", "comfortably, easily, smoothly, effortlessly, seamlessly"],
  ["adverb", "with difficulty", "awkwardly, stiffly, clumsily, painfully, arduously"],
  ["adverb", "hard", "lightly, steadily, hard, intensely, fiercely, relentlessly"],
  ["adverb", "generously", "freely, generously, lavishly, extravagantly, prodigally"],
  ["adverb", "sparingly", "cautiously, thriftily, frugally, sparingly, stingily, miserly"],
  ["adverb", "tightly", "snugly, firmly, tightly, rigidly, securely"],
  ["adverb", "loosely", "slackly, loosely, freely"],
  ["adverb", "brightly", "faintly, brightly, brilliantly, dazzlingly, radiantly"],
  ["adverb", "beautifully", "pleasantly, nicely, beautifully, exquisitely, magnificently, gorgeously"],
];
